### ISSUE TITLE
"Foreslåtte koblinger" not suggesting matches

### ISSUE THREAD

**Issue by NenadMa** [capgemini-stavanger/gi-en-jul#350]
**Describe the bug**
"Foreslåtte koblinger" is not suggesting matches when there are families and donators that could match.

**To Reproduce**
1. "Oversikt" is listing multiple "Givere" and one "Familie"
2. "Foreslåtte matcher" is not listing any families

**Expected behavior**
"Oversikt" and "Foreslåtte matcher" to use the same underlying data.

**Screenshots**
![image](https://user-images.githubusercontent.com/82819149/128136959-f48e3571-cdc6-47b8-bfc2-fc1665da2bf6.png)
![image](https://user-images.githubusercontent.com/82819149/128137021-b11e4c12-0427-4dbd-8083-3468e9d5a2ae.png)

**Comment by TheseusDeus** [comment]
This is not a bug, since the "Familie" in question here is already _suggested_ for one giver. The giver with the yellow dot on the "OVERSIKT" tab with Name: "Mitt Navn" is suggested, aka the family and that giver has been connected, but giver has not yet verified it, therefore they are yellow. The family should therefore not appear on the "Foreslåtte matcher" tab
