### ISSUE TITLE
Unable to create Admin user for Stavanger

### ISSUE THREAD

**Issue by NenadMa** [capgemini-stavanger/gi-en-jul#903]
**Describe the bug**
As a super admin user gienjuldevsuperad@gmail.com, I am not able to create admin users for Stavanger.
Error message "Kunne ikke legge til brukeren" is thrown.

**Screenshots**
![image](https://user-images.githubusercontent.com/82819149/182039786-62bc6ebd-7f53-4e32-8a05-5cf8c80468e1.png)

**Comment by hildmi** [comment]
Caused by either: 
- bug with error message, the user is created but the message is wrong 
- the password they used is not strong enough 
- the confirm password does not match the password 
- the email has been registered before

will be solved by: fixing bug in error message and  proper validation (in progress).
